Merge networks api
powsybl/pypowsybl pull request #214
Opened 2021-08-13 15:27 UTC by obrix

- [x ] The commit message follows our guidelines
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

This is the implementation for issue https://github.com/powsybl/pypowsybl/issues/212 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

No api to merge networks was available.

**What is the new behavior (if this is a feature change)?**

An api to merge networks is available, this is the core api wrapped and working the same way.

2021-08-13 15:32 UTC, obrix commented
I used a specific C struct to pass an array of ObjectHandles from C++ to java. As discusses with @geofjamg there may be a more direct way to do this by defining and using a Java structure extending PointerBase with  @CPointerTo(VoidPointer.class) annotation. I will test that soon to see if this works. The solution provided here is operational though.

2021-09-01 14:40 UTC, geofjamg requested changes

2021-09-01 14:40 UTC, geofjamg commented on java/src/main/java/com/powsybl/python/PyPowsyblApiHeader.java
> +    interface GetElementFunctionPointer extends CFunctionPointer {
We can remove it?

2021-09-02 11:57 UTC, geofjamg commented on tests/test_network.py
> +        n1 = pp.network.load(str(TEST_DIR.joinpath('empty-network.xml')))
We have to find a better test case, with mergeable networks.

2021-09-08 15:27 UTC, obrix commented on java/src/main/java/com/powsybl/python/PyPowsyblApiHeader.java
> +    interface GetElementFunctionPointer extends CFunctionPointer {
Yes, I removed it.

2021-09-14 12:02 UTC, geofjamg approved these changes

2021-09-14 12:02 UTC, merged