[WIP] Integration with python logging implementation
powsybl/pypowsybl pull request #280
Opened 2021-12-17 15:26 UTC by obrix

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

Yes this is an implementation for https://github.com/powsybl/pypowsybl/issues/142

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

This integrate java logging with logback with python logging from pypowsybl

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-03-25 13:54 UTC, geofjamg requested changes

2022-03-25 13:54 UTC, geofjamg commented on java/src/main/java/com/powsybl/python/CustomAppender.java
> +package com.powsybl.python;
Licence

2022-03-25 13:54 UTC, geofjamg commented on java/src/main/java/com/powsybl/python/CustomAppender.java
> +public class CustomAppender extends AppenderBase<ILoggingEvent> {
Author

2022-03-25 13:54 UTC, geofjamg commented on java/src/main/java/com/powsybl/python/CustomAppender.java
> +    private int logbackLevelToPythonLevel(Level l) {
You should move this along with the invert method from PyPowsyblLib into a dedicated class

2022-03-25 13:54 UTC, geofjamg commented on java/src/main/java/com/powsybl/python/CustomAppender.java
> +        logMessage.invoke(logbackLevelToPythonLevel(e.getLevel()), CTypeUtil.toCharPtr(new String(this.getEncoder().encode(e), StandardCharsets.UTF_8)));
This is not correct, the full log is serialized into a string, we should send to python all the log detail
 - date
 - message
 - logger

2022-03-25 13:54 UTC, geofjamg commented on java/src/main/java/com/powsybl/python/PyPowsyblApiLib.java
> +    static boolean readConfig = true;
?

2022-03-25 13:54 UTC, geofjamg commented on java/src/main/java/com/powsybl/python/PyPowsyblApiLib.java
> +        void invoke(int level, CCharPointer string);
Should more detailed to really dispatch to python by providing all de individual fields

2022-03-25 13:54 UTC, geofjamg commented on java/src/main/java/com/powsybl/python/PyPowsyblApiLib.java
> +    private static Level pythonLevelToLogbackLevel(int l) {
See previous comment

2022-03-25 13:54 UTC, geofjamg commented on pypowsybl/__init__.py
> +def set_logger(logger: Logger) -> None:
I don't think we should allow and bother the user to set the logger
As a first version of logging
  - log everything from Java into a "powsybl" logger (logging.getLogger('powsybl'). the problem with this approach is that we lost all Java logger infos (= java packages)
  - for a future dev, we should be able to create a python logger automatically for each Java logger

2022-03-25 13:54 UTC, geofjamg commented on pypowsybl/__init__.py
>  def set_debug_mode(debug: bool = True) -> None:
to remove

2022-03-25 13:54 UTC, geofjamg commented on tests/test_logging.py
> +# Copyright (c) 2020, RTE (http://www.rte-france.com)
2022

2022-03-25 13:54 UTC, geofjamg commented on tests/test_logging.py
> +        pypowLogger = logging.getLogger("PyPow")
Should be done automatically

2022-03-25 13:54 UTC, geofjamg commented on cpp/src/pypowsybl.h
> +    static CppToPythonLogger* mSingleton;
we prefer _xxx convention

2022-03-25 13:54 UTC, geofjamg commented on cpp/src/pypowsybl.h
> +namespace py = pybind11;
Until now we tried to have a pypowsybl namespace free of pybind11 code and all python binding is in bindings.cpp

2022-03-25 13:54 UTC, geofjamg commented on cpp/src/pypowsybl.cpp
> +    {
On C++, could you try to use same style as the existing code?

2022-03-25 13:54 UTC, geofjamg commented on cpp/src/pypowsybl.cpp
> +void CppToPythonLogger::logFromJava(int level, char* pArg) {
Is it the right place for this method? A free function?

2022-03-25 13:54 UTC, geofjamg commented on cpp/src/pypowsybl.cpp
> +    if( CppToPythonLogger::get()->loggerInitialized() ) {
There is no sync between "loggerInitialized" and "get". Could cause a crash if no luck?

2022-04-05 09:05 UTC, obrix commented on java/src/main/java/com/powsybl/python/CustomAppender.java
> +        logMessage.invoke(logbackLevelToPythonLevel(e.getLevel()), CTypeUtil.toCharPtr(new String(this.getEncoder().encode(e), StandardCharsets.UTF_8)));
You lose the formatting from logback encoder then. But can still format it from python. Is this what you have in mind ? Specifiying a custom formatter from python ?

2022-04-05 09:08 UTC, obrix commented on java/src/main/java/com/powsybl/python/PyPowsyblApiLib.java
> +    static boolean readConfig = true;
This was present before on the main branch but is no longer used. Probably an error from the multiple merging and rebasing...

2022-04-05 09:30 UTC, obrix commented on cpp/src/pypowsybl.h
> +namespace py = pybind11;
Let's move everything logging related in a pylogging.h / pylogging.cpp.

2022-04-06 08:51 UTC, obrix commented on pypowsybl/__init__.py
> +def set_logger(logger: Logger) -> None:
Done.

2022-04-19 11:31 UTC, geofjamg approved these changes

2022-04-19 11:31 UTC, merged