update to powsybl core 4.10
powsybl/pypowsybl pull request #482
Opened 2022-08-25 12:31 UTC by EtienneLt

Signed-off-by: Etienne LESOT <etienne.lesot@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

no

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

powsybl core update

**What is the new behavior (if this is a feature change)?**
use powsybl core 4.10

2022-08-25 12:43 UTC, EtienneLt commented on java/src/main/java/com/powsybl/python/network/NetworkUtil.java
> +            addLimit(limits, branch, (LoadingLimits) branch.getCurrentLimits1().orElse(null), ONE);
@sylvlecl @geofjamg I'm not sure of what should be the behavior here

2022-09-12 12:41 UTC, obrix commented
I'm trying to use this branch as a base for my next PR that use some 4.10 features but I have some issues. You seem to use a powsybl dependencies 1.3.0 snapshot version, I tried to use one locally where I just bumped core version to 4.10 RC1 but I still have issue building pypowsybl with that. Is there something else to change ? (version of other dependencies in powsybl-dependencies ?)

2022-09-12 12:43 UTC, EtienneLt commented
> I'm trying to use this branch as a base for my next PR that use some 4.10 features but I have some issues. You seem to use a powsybl dependencies 1.3.0 snapshot version, I tried to use one locally where I just bumped core version to 4.10 RC1 but I still have issue building pypowsybl with that. Is there something else to change ? (version of other dependencies in powsybl-dependencies ?)

<powsybl-core.version>4.10.0-SNAPSHOT</powsybl-core.version>
<powsybl-open-loadflow.version>0.23.0-SNAPSHOT</powsybl-open-loadflow.version>
<powsybl-single-line-diagram.version>2.13.0-SNAPSHOT</powsybl-single-line-diagram.version>

I think it works with main branches

2022-09-21 14:52 UTC, sylvlecl requested changes
Minor fixes to do on flows holder (although it has probably no impact), then OK to merge

2022-09-21 14:52 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/adders/OperationalLimitsDataframeAdder.java
> +                return branch.getNullableCurrentLimits1();
Should be 1 or 2 depending on  `side`

2022-09-21 14:52 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/adders/OperationalLimitsDataframeAdder.java
> +                return branch.getNullableActivePowerLimits1();
Should be 1 or 2 depending on  `side`

2022-09-21 14:52 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/adders/OperationalLimitsDataframeAdder.java
> +                return null;
should be `getApparentPowerLimits().orElse(null)`

2022-09-21 15:19 UTC, sylvlecl approved these changes

2022-09-21 15:32 UTC, merged