Allowing multiple dataframes extensions + exposing secondary voltage level extension
powsybl/pypowsybl pull request #564
Opened 2023-02-03 13:58 UTC by HugoKulesza

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
Issue #558

2023-02-03 14:03 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/AbstractSingleDataframeNetworkExtension.java
> + * Copyright (c) 2021-2022, RTE (http://www.rte-france.com)
2023

2023-02-03 14:04 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/AbstractSingleDataframeNetworkExtension.java
> + */
* SPDX-License-Identifier: MPL-2.0

2023-02-03 14:05 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/DataframeKey.java
> + * file, You can obtain one at http://mozilla.org/MPL/2.0/.
same

2023-02-03 14:06 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/DataframeKey.java
> +public class DataframeKey {
it is only used for extension ? maybe it should have a more explicit name ?

2023-02-03 14:06 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeAdder.java
> + */
same for all new headers

2023-02-03 14:12 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeAdder.java
> +            }
should we check if zoneCount is equal to 0 ?

2023-02-03 14:14 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeProvider.java
> +                "index : ");
I think it would be great to add that 2 dataframes are needed and their attributes definitions

2023-02-03 14:16 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/AbstractSingleDataframeNetworkExtension.java
> +        return new ArrayList<>();
maybe Collections.emptyList() is better ? @sylvlecl ?

2023-02-07 13:35 UTC, sylvlecl requested changes
Nice work overall :)

2 kinds of comments:
- "cosmetic" suggestions
- additional feature to be implemented: the "update" part, and less importantly the parsing of comma separated bus IDs. Actually those 2 things could also be done in a further pull request, but this should not be too much code

2023-02-07 13:35 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/extensions/ExtensionDataframeKey.java
> +    private Optional<String> tableName;
The common practice is to use `Optional` only as a return type, and simply use "nullable" values in function argument and field classes. (see sonar rule about it). Basically wrapping in an optional is useful mostly for chaining methods on the return value.
--> let's keep with this practice by removing the optional here and in the constructor

2023-02-07 13:35 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/extensions/ExtensionDataframeKey.java
> +    private String extensionName;
all fields can be `final`

2023-02-07 13:35 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/extensions/ExtensionDataframeKey.java
> +        this.extensionName = extensionName;
we can add a non-null check here (`Objects.requireNonNull`)

2023-02-07 13:35 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/extensions/ExtensionDataframeKey.java
> +        this.hashCode = Objects.hash(extensionName, tableName);
it's not usual to cache it in a field of the class, but why not! (I guess there is a kind of tradeoff between memory used by the class and performance, and actually this class is really meant to be used as a key in hashmap, so it makes sense)

2023-02-07 13:35 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/extensions/AbstractSingleDataframeNetworkExtension.java
> +    public List<Optional<String>> getExtensionTableNames() {
In collection classes too it's a little unusual to use optionals, I would prefer plain strings instead. Actually in this list in particular, I think we should not have null values at all.
(Note that it's possible that some map implementations don't support null key, but I think for ex. `HashMap` does)

2023-02-07 13:35 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeProvider.java
> +        private SecondaryVoltageControl.ControlUnit unit;
fields can be final

2023-02-07 13:35 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeProvider.java
> +                        .strings("bus_ids", zone -> zone.getPilotPoint().getBusbarSectionsOrBusesIds().get(0)) // TODO : parser liste ids
indeed there is a small todo here :)
just joining the strings using a "," should be OK

2023-02-07 13:35 UTC, sylvlecl commented on java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeAdder.java
> +                SecondaryVoltageControl.PilotPoint pilotPoint = new SecondaryVoltageControl.PilotPoint(List.of(busIds.get(zone)),
I think we can split on "," here to get a list of IDs

2023-02-07 13:35 UTC, sylvlecl commented on tests/test_network_extensions.py
> +
we could add a test to update the values of `target_v` and `participate` with `update_extensions`

2023-02-07 13:35 UTC, sylvlecl commented on java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
> +            NetworkDataframeMapper mapper = NetworkDataframes.getExtensionDataframeMapper(name, Optional.empty());
Actually we should also adapt this "update" part so that "update_extensions" also works with the additional table argument

2023-02-09 09:30 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/ExtensionDataframeKey.java
> +    public String getTableName() {
that 's here where it should return an Optional I'll fix it

2023-02-09 09:41 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeProvider.java
> +            this.zoneName = zoneName;
maybe a check non null can be added ?

2023-02-09 10:02 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/network/extensions/ExtensionDataframeKey.java
> +    public String getTableName() {
indeed the method is not used I delete

2023-02-10 10:08 UTC, sylvlecl approved these changes

2023-02-10 10:11 UTC, EtienneLt approved these changes

2023-02-10 10:29 UTC, merged