Wrap NetworkAreaDiagram.getDisplayedVoltageLevels
powsybl/pypowsybl pull request #656
Opened 2023-09-27 08:26 UTC by tadam50

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
Feature

**What is the current behavior?**
No access to NetworkAreaDiagram.getDisplayedVoltageLevels

**What is the new behavior (if this is a feature change)?**
User access to NetworkAreaDiagram.getDisplayedVoltageLevels

2023-09-29 09:42 UTC, So-Fras requested changes
Add also:
`def get_network_area_diagram_displayed_voltageLevels(network: JavaHandle, voltage_level_ids: Union[str, List[str]], depth: int) -> List[str]: ...`
in _pypowsybl.pyi

I did this review by including your changes in the #632 PR and overwriting the diagram related versions in the pom (all of this locally of course)

2023-09-29 09:42 UTC, So-Fras commented on cpp/src/bindings.cpp
> +          py::arg("network"), py::arg("voltage_level_ids"), py::arg("depth")));
Extra parenthesis to remove after "depth" --> `...arg("depth"));`

2023-09-29 09:42 UTC, So-Fras commented on cpp/src/pypowsybl.cpp
> +    auto displayedVoltageLevelIdsArrayPtr = callJava<array*>(::getDisplayedVoltageLevels, network, voltageLevelIdPtr.get(), voltageLevelIds.size(), depth);
`(::getNetworkAreaDiagramDisplayedVoltageLevels, network, ...`

2023-09-29 09:42 UTC, So-Fras commented on java/src/main/java/com/powsybl/python/network/NetworkAreaDiagramUtil.java
> +    public static List<String> getDisplayedVoltageLevels(Network network, List<String> voltageLevelIds, int depth) {
`getNetworkAreaDiagramDisplayedVoltageLevels(Network network, List<String> voltageLevelIds, int depth)`

2023-09-29 09:42 UTC, So-Fras commented on java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
> +    public static PyPowsyblApiHeader.ArrayPointer<CCharPointerPointer> getDisplayedVoltageLevels(IsolateThread thread, ObjectHandle networkHandle, CCharPointerPointer voltageLevelIdsPointer,
`getNetworkAreaDiagramDisplayedVoltageLevels(IsolateThread thread...)`

2023-09-29 09:42 UTC, So-Fras commented on java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
> +        });
`getNetworkAreaDiagramDisplayedVoltageLevels(network, ...)`

2023-10-09 13:46 UTC, So-Fras approved these changes

2023-10-17 20:46 UTC, geofjamg requested changes
Documentation is missing

2023-10-24 07:18 UTC, EtienneLt approved these changes

2023-10-24 07:20 UTC, merged