add tooltip enabled parameter
powsybl/pypowsybl pull request #684
Opened 2023-12-06 14:04 UTC by EtienneLt

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?**
feature

**What is the new behavior (if this is a feature change)?**
add new sld parameter to display tooltip

2023-12-06 15:15 UTC, So-Fras requested changes

2023-12-06 15:15 UTC, So-Fras commented on cpp/src/bindings.cpp
> +        .def_readwrite("tool_tip_enabled", &pypowsybl::SldParameters::tool_tip_enabled);
I would put the `tool_tip_enabled` line just below the `nodes_infos` one because tool_tip_enabled is an `SvgParameters` field (as well as use_name, center_name, diagonal_label and nodes_infos).
The same remark applies to the 9 modified files of this PR.

2023-12-06 15:22 UTC, EtienneLt commented on cpp/src/bindings.cpp
> +        .def_readwrite("tool_tip_enabled", &pypowsybl::SldParameters::tool_tip_enabled);
ok I'll change that

2023-12-11 08:56 UTC, So-Fras approved these changes

2023-12-11 14:22 UTC, geofjamg requested changes
tooltip is a word, it looks bad to have tool_tip everywhere

2023-12-11 14:23 UTC, geofjamg commented on java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
> +                .setStyleProviderFactory(sldParametersPtr.isTopologicalColoring() ? new DefaultStyleProviderFactory() :
the : should be in that case just under the ?

2023-12-12 14:00 UTC, EtienneLt commented on java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
> +                .setStyleProviderFactory(sldParametersPtr.isTopologicalColoring() ? new DefaultStyleProviderFactory() :
ok

2023-12-13 10:29 UTC, geofjamg approved these changes

2023-12-13 10:29 UTC, merged