add missing attributes for per unit view
powsybl/pypowsybl pull request #714
Opened 2024-02-20 15:59 UTC by EtienneLt

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-02-22 08:11 UTC, geofjamg reviewed
Did you check that all attributes that are now accessible are correctly per-united? For example target_v for transformer 2 and 3, shunt ? Also all target p and q (hvdc lines etc ) ?

2024-02-22 08:15 UTC, EtienneLt commented
> Did you check that all attributes that are now accessible are correctly per-united? For example target_v for transformer 2 and 3, shunt ? Also all target p and q (hvdc lines etc ) ?

I will add some tests

2024-02-22 08:22 UTC, EtienneLt commented
> Did you check that all attributes that are now accessible are correctly per-united? For example target_v for transformer 2 and 3, shunt ? Also all target p and q (hvdc lines etc ) ?

well all targetv for transformer and target p ans q for hvdc are default attributes so they were already perunit 
I added the non default attributes for generators and vsc stations (max_q_at_p, ....)

2024-02-22 08:25 UTC, EtienneLt commented
update_ratio_tap_changers is missing

2024-02-23 07:30 UTC, geofjamg approved these changes

2024-02-26 08:42 UTC, geofjamg requested changes

2024-02-26 08:42 UTC, geofjamg commented on pypowsybl/network/impl/perunit.py
> +        regulated_side_nominal_voltage = nominal_v2
Why do we get a different peruniting depending on if we have the target_v inside the dataframe?

2024-05-16 06:32 UTC, closed without merging