add optional on getRegulatedSide
powsybl/pypowsybl pull request #717
Opened 2024-02-23 09:26 UTC by EtienneLt

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
no

**What kind of change does this PR introduce?**
Bug fix

**What is the current behavior?**
if the regulated side is present when creating a twt there is a null pointer exception

2024-02-26 08:38 UTC, geofjamg requested changes
A unit test showing the NPE would be welcome.

2024-02-26 08:38 UTC, geofjamg commented on java/src/main/java/com/powsybl/dataframe/loadflow/validation/Validations.java
> +                    if (d.getRegulatedSide().isPresent()) {
Could by done using .map(...)

2024-02-26 15:06 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/loadflow/validation/Validations.java
> +                    if (d.getRegulatedSide().isPresent()) {
I dont know how to test in python I cant set a null regulated side on a ratio tap changer

2024-02-29 15:14 UTC, EtienneLt commented on java/src/main/java/com/powsybl/dataframe/loadflow/validation/Validations.java
> +                    if (d.getRegulatedSide().isPresent()) {
done

2024-03-07 09:20 UTC, geofjamg approved these changes

2024-03-07 09:22 UTC, merged