Add dynamic models mapping
powsybl/pypowsybl pull request #867
Opened 2024-10-16 14:38 UTC by Lisrte

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**
Mapping for all dynamic and event models implemented by Powsybl-Dynawo in 2.6.0

**Does this PR introduce a breaking change or deprecate an API?**
- [x] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [x] The *Breaking Change* or *Deprecated* label has been added
- [x] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

Replace : 
- `add_alpha_beta_load` with `add_base_load` with _LoadAlphaBeta_ as `model_name`
- `add_one_transformer_load` with `add_load_one_transformer`
- `add_generator_synchronous_three_windings` with `add_synchronous_generator` with _GeneratorSynchronousThreeWindings_ as `model_name`
- `add_generator_synchronous_three_windings_proportional_regulations` with `add_synchronous_generator` with _GeneratorSynchronousThreeWindingsProportionalRegulations_ as `model_name`
- `add_generator_synchronous_four_windings` with `add_synchronous_generator` with _GeneratorSynchronousFourWindings_ as `model_name`
- `add_generator_synchronous_four_windings_proportional_regulations` with `add_synchronous_generator` with _GeneratorSynchronousFourWindingsProportionalRegulations_ as `model_name`
- `add_current_limit_automaton`  with `add_overload_management_system`

2024-11-19 10:19 UTC, HugoKulesza requested changes

2024-11-19 10:19 UTC, HugoKulesza commented on java/src/main/java/com/powsybl/python/dynamic/DynamicSimulationCFunctions.java
> + * @author Nicolas Pierre <nicolas.pierre@artelys.com>
put back the literal tag

2024-11-19 10:19 UTC, HugoKulesza commented on java/src/main/java/com/powsybl/python/dynamic/PythonCurveSupplier.java
> +    }
It doesn't seem to be used ?

2024-11-19 10:19 UTC, HugoKulesza commented on java/src/main/java/com/powsybl/python/dynamic/PythonDynamicModelsSupplier.java
> + * @author Nicolas Pierre <nicolas.pierre@artelys.com>
Literal tag to restore here too

2024-11-19 10:19 UTC, HugoKulesza commented on java/src/main/java/com/powsybl/python/dynamic/PythonEventModelsSupplier.java
> + * @author Nicolas Pierre <nicolas.pierre@artelys.com>
same here

2024-11-19 10:19 UTC, HugoKulesza commented on java/src/main/java/com/powsybl/python/dynamic/DynamicSimulationContext.java
> + * @author Nicolas Pierre <nicolas.pierre@artelys.com>
same here

2024-11-19 10:19 UTC, HugoKulesza commented on java/src/main/java/com/powsybl/dataframe/dynamic/adders/DynamicMappingHandler.java
> +        // TODO return ModelInfo directly
Is this TODO still relevant ? (I'm not sure what it means)

2024-11-20 13:19 UTC, Lisrte commented on java/src/main/java/com/powsybl/dataframe/dynamic/adders/DynamicMappingHandler.java
> +        // TODO return ModelInfo directly
I'll remove it an keep it for another PR

2024-11-20 13:22 UTC, Lisrte commented on java/src/main/java/com/powsybl/python/dynamic/PythonCurveSupplier.java
> +    }
It's not used at the moment. I remove it for now and it will be added in another PR.

2024-11-21 15:18 UTC, HugoKulesza approved these changes

2024-11-28 12:49 UTC, merged