Get import supported extensions
powsybl/pypowsybl pull request #889
Opened 2024-11-07 14:38 UTC by geofjamg

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Feature

**What is the new behavior (if this is a feature change)?**
We can get list of supported import file extensions. 

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-11-13 13:23 UTC, HugoKulesza requested changes

2024-11-13 13:23 UTC, HugoKulesza commented on tests/test_network.py
> +    extenssions = pp.network.get_import_supported_extensions()
Just a 's' to remove here

2024-11-19 13:13 UTC, geofjamg commented on tests/test_network.py
> +    extenssions = pp.network.get_import_supported_extensions()
Fixed

2024-11-19 14:52 UTC, HugoKulesza approved these changes

2024-11-19 14:52 UTC, merged